### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by Ticklezz** [toppk/gnome-shell-extension-openweather#4]
I know there is a method to force this to 45, I just am unsure of how to do that. Can anyone give some guidance on what to do?

**Comment by christopherdriscoll** [comment]
@Ticklezz - Which distribution (and version of distribution) are you running?

**Comment by Ticklezz** [comment]
> @Ticklezz - Which distribution (and version of distribution) are you running? I am on ubuntu 23.10.

**Comment by christopherdriscoll** [comment]
Hopefully these steps help.  I added the `gnome-shell-extension-manager` package if it's not already installed to make managing extensions easier.  The steps will create a `src` directory in your home (`~`) directory, then clone the git repo, compile, then install the extension.

You may need to log out and back in, or reload GNOME by pressing Alt+F2, then enter `r` in the small dialog box, then press Enter.  That will reload gnome under X11; if you're running Wayland the log out and back in method should work.

```
sudo apt -y update
sudo apt install dconf-gsettings-backend gnome-shell-extension-prefs git build-essential gettext libsoup-3.0-dev gnome-shell-extension-manager
mkdir ~/src
cd ~/src
git clone https://github.com/toppk/gnome-shell-extension-openweather
cd gnome-shell-extension-openweather
make
make install
```

**Comment by Ticklezz** [comment]
> Hopefully these steps help. I added the `gnome-shell-extension-manager` package if it's not already installed to make managing extensions easier. The steps will create a `src` directory in your home (`~`) directory, then clone the git repo, compile, then install the extension.
> 
> You may need to log out and back in, or reload GNOME by pressing Alt+F2, then enter `r` in the small dialog box, then press Enter. That will reload gnome under X11; if you're running Wayland the log out and back in method should work.
> 
> ```
> sudo apt -y update
> sudo apt install dconf-gsettings-backend gnome-shell-extension-prefs git build-essential gettext libsoup-3.0-dev gnome-shell-extension-manager
> mkdir ~/src
> cd ~/src
> git clone https://github.com/toppk/gnome-shell-extension-openweather
> cd gnome-shell-extension-openweather
> make
> make install
> ```

I wasn't expecting that. Thanks a bunch.
